# -*- coding: utf-8 -*-
"""Desafio 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XweXAeUZ87kvcT6mmM-f6Ro4DXsgMM6S
"""

#Desafio
n1 = float(input('Digite um número: '))
n2 = float(input('Digite um número para ser ordenadamente operado com o primeiro: '))
sum = n1+n2
diff = n1-n2
mult = n1*n2
div= n1/n2
div_exact = n1//n2
exp = n1**n2

print(f'''A soma desses dois números é {sum}

A diferença entre esses dois números é {diff}

A multiplicação desses dois números é {mult}

A divisão desses dois números é {div}

A divisão exata desses dois números é {div_exact}

A exponenciação desses dois números, tendo o primeiro como base e o segundo como expoente é {exp}''')